require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FitnessMetricsController do

  # This should return the minimal set of attributes required to create a valid
  # FitnessMetric. As you add validations to FitnessMetric, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "metricsID" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FitnessMetricsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all fitness_metrics as @fitness_metrics" do
      fitness_metric = FitnessMetric.create! valid_attributes
      get :index, {}, valid_session
      assigns(:fitness_metrics).should eq([fitness_metric])
    end
  end

  describe "GET show" do
    it "assigns the requested fitness_metric as @fitness_metric" do
      fitness_metric = FitnessMetric.create! valid_attributes
      get :show, {:id => fitness_metric.to_param}, valid_session
      assigns(:fitness_metric).should eq(fitness_metric)
    end
  end

  describe "GET new" do
    it "assigns a new fitness_metric as @fitness_metric" do
      get :new, {}, valid_session
      assigns(:fitness_metric).should be_a_new(FitnessMetric)
    end
  end

  describe "GET edit" do
    it "assigns the requested fitness_metric as @fitness_metric" do
      fitness_metric = FitnessMetric.create! valid_attributes
      get :edit, {:id => fitness_metric.to_param}, valid_session
      assigns(:fitness_metric).should eq(fitness_metric)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FitnessMetric" do
        expect {
          post :create, {:fitness_metric => valid_attributes}, valid_session
        }.to change(FitnessMetric, :count).by(1)
      end

      it "assigns a newly created fitness_metric as @fitness_metric" do
        post :create, {:fitness_metric => valid_attributes}, valid_session
        assigns(:fitness_metric).should be_a(FitnessMetric)
        assigns(:fitness_metric).should be_persisted
      end

      it "redirects to the created fitness_metric" do
        post :create, {:fitness_metric => valid_attributes}, valid_session
        response.should redirect_to(FitnessMetric.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fitness_metric as @fitness_metric" do
        # Trigger the behavior that occurs when invalid params are submitted
        FitnessMetric.any_instance.stub(:save).and_return(false)
        post :create, {:fitness_metric => { "metricsID" => "invalid value" }}, valid_session
        assigns(:fitness_metric).should be_a_new(FitnessMetric)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FitnessMetric.any_instance.stub(:save).and_return(false)
        post :create, {:fitness_metric => { "metricsID" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fitness_metric" do
        fitness_metric = FitnessMetric.create! valid_attributes
        # Assuming there are no other fitness_metrics in the database, this
        # specifies that the FitnessMetric created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FitnessMetric.any_instance.should_receive(:update).with({ "metricsID" => "1" })
        put :update, {:id => fitness_metric.to_param, :fitness_metric => { "metricsID" => "1" }}, valid_session
      end

      it "assigns the requested fitness_metric as @fitness_metric" do
        fitness_metric = FitnessMetric.create! valid_attributes
        put :update, {:id => fitness_metric.to_param, :fitness_metric => valid_attributes}, valid_session
        assigns(:fitness_metric).should eq(fitness_metric)
      end

      it "redirects to the fitness_metric" do
        fitness_metric = FitnessMetric.create! valid_attributes
        put :update, {:id => fitness_metric.to_param, :fitness_metric => valid_attributes}, valid_session
        response.should redirect_to(fitness_metric)
      end
    end

    describe "with invalid params" do
      it "assigns the fitness_metric as @fitness_metric" do
        fitness_metric = FitnessMetric.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FitnessMetric.any_instance.stub(:save).and_return(false)
        put :update, {:id => fitness_metric.to_param, :fitness_metric => { "metricsID" => "invalid value" }}, valid_session
        assigns(:fitness_metric).should eq(fitness_metric)
      end

      it "re-renders the 'edit' template" do
        fitness_metric = FitnessMetric.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FitnessMetric.any_instance.stub(:save).and_return(false)
        put :update, {:id => fitness_metric.to_param, :fitness_metric => { "metricsID" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fitness_metric" do
      fitness_metric = FitnessMetric.create! valid_attributes
      expect {
        delete :destroy, {:id => fitness_metric.to_param}, valid_session
      }.to change(FitnessMetric, :count).by(-1)
    end

    it "redirects to the fitness_metrics list" do
      fitness_metric = FitnessMetric.create! valid_attributes
      delete :destroy, {:id => fitness_metric.to_param}, valid_session
      response.should redirect_to(fitness_metrics_url)
    end
  end

end
